spring:
  datasource:
    driverClassName: org.h2.Driver
    jdbc-url: jdbc:h2:~/ticket_pc_v20
    username: CC6rMfYvkIPd0fl/pEyLMQ==
    password: IFRseW/wJsfpfeDfHRuy7w==
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        hbm2ddl.auto: update
        format_sql: true
        physical_naming_strategy: 'com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy'
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
  gateway: https://vinvoice.viettel.vn/api
  crmUrl: https://vinvoice.viettel.vn/api/services/companyinfo/api/_search/companies
  web-client: https://vinvoice.viettel.vn
  cur-version: v0.2.1
logging:
  level:
    ROOT: INFO
    com.uni.ticket: INFO
#    org.hibernate: DEBUG
  file:
    name: ${user.home}/logs/pc-ticket.log
    max-size: 10MB
    max-history: 10
    total-size-cap: 100MB
  pattern:
    rolling-file-name: ${user.home}/logs/pc-ticket.log.%d{yyyy-MM-dd}.%i.gz